### ISSUE TITLE
Unmarshal errors with multiple exercise functions

### ISSUE THREAD

**Issue by obitech** [muxinc/mux-go#16]
Hey guys, I just tried your [metrics example code](https://github.com/muxinc/mux-go/blob/master/examples/data/metrics/exercise-metrics.go) and three out of five examples don't work. I'm running on `go1.14.4 darwin/amd64` with mux-go `v0.8.0`.

Input:
```go
bdvopts := muxgo.ListBreakdownValuesParams{GroupBy: "browser", Timeframe: []string{"7:days"}}
bdv, err := client.MetricsApi.ListBreakdownValues("video_startup_time", muxgo.WithParams(&bdvopts))
```
Error:
```
err: json: cannot unmarshal string into Go struct field BreakdownValue.data.negative_impact of type int32

exit status 255
```
---
Input:
```go
ovopts := muxgo.GetOverallValuesParams{Timeframe: []string{"7:days"}}
ov, err := client.MetricsApi.GetOverallValues("video_startup_time", muxgo.WithParams(&ovopts))
```
Error:
```
err: json: cannot unmarshal string into Go struct field OverallValues.data.total_views of type int64

exit status 255
```
---
Input:
```go
iopts := muxgo.ListInsightsParams{Timeframe: []string{"7:days"}}
is, err := client.MetricsApi.ListInsights("video_startup_time", muxgo.WithParams(&iopts))
```
Error:
```
err: json: cannot unmarshal string into Go struct field Insight.data.total_views of type int64

exit status 255
```
--- 

The [list-filter-values](https://github.com/muxinc/mux-go/blob/master/examples/data/filters/exercise-filters.go) exercise also doesn't work:

Input:
```go
fp := muxgo.ListFilterValuesParams{Timeframe: []string{"7:days"}}
fv, err := client.FiltersApi.ListFilterValues("browser", muxgo.WithParams(&fp))
```
Error:
```
err: json: cannot unmarshal string into Go struct field FilterValue.data.total_count of type int64

exit status 255
```

**Comment by GeneticGenesis** [comment]
Hey @obitech, thanks for reaching out on this. 

Unfortunately at the moment this is an expected failure, we're going to be changing some server side responses to fix this incompatibility, I'll chase this internally today.

Thanks again, I'll assign this to me and drop an update here when I have one.

**Comment by GeneticGenesis** [comment]
Hi @obitech so sorry I forgot to close this when I fixed this on our end, I think I pinged you in Slack. 

#19 

Let me know if you have any other issues!
