### ISSUE TITLE
V3.2.0 resolves to V1.1.0. Update go.mod file.

### ISSUE THREAD

**Issue by nickolasteixeira** [muxinc/mux-go#37]
I noticed an issue when getting the latest muxgo sdk, v3.2.0. I first tried to use the [PlaybackRestrictionsApiService](https://github.com/muxinc/mux-go/blob/064043114709e4471077003ce129d1d6f3d6b21b/client.go#L82) in the go sdk to create a playback restriction, but wasn't able to. It resolves to version v1.1.0 and not the latest version. 

```bash
go get github.com/muxinc/mux-go 
```
I believe the reason is because of the [semantic versioning for go module versions](https://github.com/golang/go/issues/35732#issuecomment-557227639). 

I think a simple fix would be just adding this line of code to the `go.mod` file:

So this [line of code](https://github.com/muxinc/mux-go/blob/064043114709e4471077003ce129d1d6f3d6b21b/go.mod#L1) would be:

```go
module github.com/muxinc/mux-go/v3
```

Or am I doing something incorrectly here?

Here are a few references and examples from other 3rd party SDKs (packages)
- https://github.com/golang/go/issues/35732#issuecomment-584319096
- Mailgun-go package doing the same thing for their golang sdk in their [go.mod file.](https://github.com/mailgun/mailgun-go/blob/677f15d79dfdfda74a752b2a308e41c6413cd296/go.mod#L1)

**Comment by nickolasteixeira** [comment]
Hi @philcluff, I see that this issue: https://github.com/muxinc/mux-go/issues/38#issuecomment-1031535209 was fixed by the v4.0.0 release, but when running `go get github.com/muxinc/mux-go `, it still defaults to v1.1.1.

Is this something that was also going to get fixed in the new release? If not, how would you suggest getting the new v4.0.0 release? Vendoring?

**Comment by philcluff** [comment]
Hey @nickolasteixeira, I've asked the team to take a look at this. 

Thanks.

**Comment by philcluff** [comment]
Hey @nickolasteixeira 

Please can you try:

```
go get github.com/muxinc/mux-go/v4
```

And updating your import lines to:

```
import "gthub.com/muxinc/mux-go/v4"
```

And see if that works for you?

If you get issues on the `go get`, please run `go clean --modcache` and then try again.

Thanks!

**Comment by nickolasteixeira** [comment]
@philcluff Works now. Thank you! Will ping you if I spot anything else that might need updating.

**Comment by philcluff** [comment]
Great! Thanks @nickolasteixeira !
