### ISSUE TITLE
Missing "connected" property on LiveStream

### ISSUE THREAD

**Issue by MattNewberry** [muxinc/mux-go#39]
Though no mention is made in the API docs, a property which has been very helpful to me is `connected` on `LiveStream` as typically found in webhook data.

This property is very helpful in driving UI indicators for when a stream goes live.

This property is currently missing on the `LiveStream` model.

For example:

```
{
  "stream_key": "******",
  "status": "active",
  "recording": true,
  "playback_ids": [
    {
      "policy": "public",
      "id": "ljCTZK94b7ADmwCFR00KyLMda11jx21sTEKBJIxYIpBs"
    }
  ],
  "passthrough": "GHC9jb6DOsbHZs4NAifM",
  "new_asset_settings": {
    "playback_policies": [
      "public"
    ]
  },
  "low_latency": true,
  "latency_mode": "low",
  "id": "joIgTGuMkyk00006jIsWVmukX007PTDOnB01uqiYUlqUUfA",
  "created_at": 1644527397,
  "connected": true,
  "active_asset_id": "OX5xoQAo2NBqZdFzQr8MpZ532vN01wHXfMO2bXMvagY00"
}
```

**Comment by philcluff** [comment]
Hi @MattNewberry, thanks for raising this.

I've passed this along to the product team for consideration as we evolve the documentation and models around webhooks, but it's not something we can immediately implement. 

Thanks again.
